### ISSUE TITLE
Example of use please

### ISSUE THREAD

**Issue by delmicio** [tsari/docker-entrypoint#1]
I've been trying the past two days to include auto composer commands in my docker-compose file and failing.

Seems like your entrypoint can solve this issue but I don't know how to use it.

Could you provide an example with composer?

**Comment by tsari** [comment]
Hi.

First of all please have al look at https://github.com/tsari/dockerfiles/tree/master/composer. In the Dockerfile I add the entry point script and make it executable.

I know you are able to set the entry point via docker-compose as well, but there might problems because the file isn't yet executable.

But here is an example (untested and directly out of brain):

```
volumes:
 - ./folder/with/entrypoint/inside/entrypoint.sh:/usr/local/bin/entrypoint.sh
entrypoint:
 - bash
 - /usr/local/bin/entrypoint.sh
 - composer
 - update
```

You have to add all necessary environment variables that are used in the entry point script as well. In this way it will create a user inside the image container that behaves like the user that startet the script.

https://github.com/tsari/dockerfiles/blob/master/composer/composer


Hope this helps.

**Comment by tsari** [comment]
It seems that I couldn't help.
